import { buildTheme, darkSurfaces, lightSurfaces } from './build.ts';

/** 7 coordinated MD3 brand palettes with tinted page backgrounds. */

export const oceanTheme = buildTheme({
  id: 'ocean',
  label: '海洋',
  swatch: '#1565c0',
  accent: '#4fc3f7',
  surfaces: {
    light: lightSurfaces('#f3f7fc', {
      low: '#eaf1f9',
      container: '#e2ebf5',
      high: '#d9e4f0',
      highest: '#d0dceb',
      variant: '#d5e3f0',
      dim: '#d0dceb',
    }),
    dark: darkSurfaces('#121820', {
      low: '#181f29',
      container: '#1c2430',
      high: '#262f3c',
      highest: '#313b4a',
      bright: '#2a3442',
      variant: '#3d4a5c',
    }),
  },
  light: {
    primary: '#1565c0',
    'on-primary': '#ffffff',
    'primary-container': '#d1e4ff',
    'on-primary-container': '#001d36',
    'primary-fixed': '#d1e4ff',
    'primary-fixed-dim': '#9ecaff',
    'on-primary-fixed': '#001d36',
    'on-primary-fixed-variant': '#00497d',
    'inverse-primary': '#9ecaff',
    secondary: '#535f70',
    'on-secondary': '#ffffff',
    'secondary-container': '#d7e3f7',
    'on-secondary-container': '#101c2b',
    'secondary-fixed': '#d7e3f7',
    'secondary-fixed-dim': '#bbc7db',
    'on-secondary-fixed': '#101c2b',
    'on-secondary-fixed-variant': '#3c4858',
    tertiary: '#006879',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#a9edff',
    'on-tertiary-container': '#001f26',
    'tertiary-fixed': '#a9edff',
    'tertiary-fixed-dim': '#4fc3f7',
    'on-tertiary-fixed': '#001f26',
    'on-tertiary-fixed-variant': '#004e5c',
    'surface-tint': '#1565c0',
  },
  dark: {
    primary: '#9ecaff',
    'on-primary': '#003258',
    'primary-container': '#00497d',
    'on-primary-container': '#d1e4ff',
    'primary-fixed': '#d1e4ff',
    'primary-fixed-dim': '#9ecaff',
    'on-primary-fixed': '#001d36',
    'on-primary-fixed-variant': '#00497d',
    'inverse-primary': '#1565c0',
    secondary: '#bbc7db',
    'on-secondary': '#253140',
    'secondary-container': '#3c4858',
    'on-secondary-container': '#d7e3f7',
    'secondary-fixed': '#d7e3f7',
    'secondary-fixed-dim': '#bbc7db',
    'on-secondary-fixed': '#101c2b',
    'on-secondary-fixed-variant': '#3c4858',
    tertiary: '#4fc3f7',
    'on-tertiary': '#003641',
    'tertiary-container': '#004e5c',
    'on-tertiary-container': '#a9edff',
    'tertiary-fixed': '#a9edff',
    'tertiary-fixed-dim': '#4fc3f7',
    'on-tertiary-fixed': '#001f26',
    'on-tertiary-fixed-variant': '#004e5c',
    'surface-tint': '#9ecaff',
  },
});

export const forestTheme = buildTheme({
  id: 'forest',
  label: '森林',
  swatch: '#2e7d32',
  accent: '#81c784',
  surfaces: {
    light: lightSurfaces('#f4faf4', {
      low: '#eaf5ea',
      container: '#e1efe1',
      high: '#d7e8d7',
      highest: '#cee1ce',
      variant: '#d4e5d4',
      dim: '#cee1ce',
    }),
    dark: darkSurfaces('#141a14', {
      low: '#1a221a',
      container: '#1e281e',
      high: '#283228',
      highest: '#323d32',
      bright: '#2a352a',
      variant: '#3d4a3d',
    }),
  },
  light: {
    primary: '#2e7d32',
    'on-primary': '#ffffff',
    'primary-container': '#c8e6c9',
    'on-primary-container': '#002204',
    'primary-fixed': '#c8e6c9',
    'primary-fixed-dim': '#a5d6a7',
    'on-primary-fixed': '#002204',
    'on-primary-fixed-variant': '#1b5e20',
    'inverse-primary': '#a5d6a7',
    secondary: '#52634f',
    'on-secondary': '#ffffff',
    'secondary-container': '#d5e8cf',
    'on-secondary-container': '#101f0f',
    'secondary-fixed': '#d5e8cf',
    'secondary-fixed-dim': '#b9ccb3',
    'on-secondary-fixed': '#101f0f',
    'on-secondary-fixed-variant': '#3b4b38',
    tertiary: '#38656a',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#bcebf0',
    'on-tertiary-container': '#001f23',
    'tertiary-fixed': '#bcebf0',
    'tertiary-fixed-dim': '#81c784',
    'on-tertiary-fixed': '#001f23',
    'on-tertiary-fixed-variant': '#1e4d52',
    'surface-tint': '#2e7d32',
  },
  dark: {
    primary: '#a5d6a7',
    'on-primary': '#00390a',
    'primary-container': '#1b5e20',
    'on-primary-container': '#c8e6c9',
    'primary-fixed': '#c8e6c9',
    'primary-fixed-dim': '#a5d6a7',
    'on-primary-fixed': '#002204',
    'on-primary-fixed-variant': '#1b5e20',
    'inverse-primary': '#2e7d32',
    secondary: '#b9ccb3',
    'on-secondary': '#253423',
    'secondary-container': '#3b4b38',
    'on-secondary-container': '#d5e8cf',
    'secondary-fixed': '#d5e8cf',
    'secondary-fixed-dim': '#b9ccb3',
    'on-secondary-fixed': '#101f0f',
    'on-secondary-fixed-variant': '#3b4b38',
    tertiary: '#81c784',
    'on-tertiary': '#00363b',
    'tertiary-container': '#1e4d52',
    'on-tertiary-container': '#bcebf0',
    'tertiary-fixed': '#bcebf0',
    'tertiary-fixed-dim': '#81c784',
    'on-tertiary-fixed': '#001f23',
    'on-tertiary-fixed-variant': '#1e4d52',
    'surface-tint': '#a5d6a7',
  },
});

export const blossomTheme = buildTheme({
  id: 'blossom',
  label: '樱花',
  swatch: '#c2185b',
  accent: '#f48fb1',
  surfaces: {
    light: lightSurfaces('#fdf5f8', {
      low: '#faebf0',
      container: '#f6e2e9',
      high: '#f1d8e2',
      highest: '#eccfd9',
      variant: '#f0d5df',
      dim: '#eccfd9',
    }),
    dark: darkSurfaces('#1c1418', {
      low: '#241a1f',
      container: '#2a1f25',
      high: '#352930',
      highest: '#40333b',
      bright: '#32262e',
      variant: '#4a3a42',
    }),
  },
  light: {
    primary: '#c2185b',
    'on-primary': '#ffffff',
    'primary-container': '#ffd9e2',
    'on-primary-container': '#3e001d',
    'primary-fixed': '#ffd9e2',
    'primary-fixed-dim': '#ffb1c8',
    'on-primary-fixed': '#3e001d',
    'on-primary-fixed-variant': '#8e0040',
    'inverse-primary': '#ffb1c8',
    secondary: '#74565c',
    'on-secondary': '#ffffff',
    'secondary-container': '#ffd9e2',
    'on-secondary-container': '#2b151a',
    'secondary-fixed': '#ffd9e2',
    'secondary-fixed-dim': '#e3bdc4',
    'on-secondary-fixed': '#2b151a',
    'on-secondary-fixed-variant': '#5a3f45',
    tertiary: '#7c5635',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#ffdcc2',
    'on-tertiary-container': '#2e1500',
    'tertiary-fixed': '#ffdcc2',
    'tertiary-fixed-dim': '#f48fb1',
    'on-tertiary-fixed': '#2e1500',
    'on-tertiary-fixed-variant': '#613f20',
    'surface-tint': '#c2185b',
  },
  dark: {
    primary: '#ffb1c8',
    'on-primary': '#650033',
    'primary-container': '#8e0040',
    'on-primary-container': '#ffd9e2',
    'primary-fixed': '#ffd9e2',
    'primary-fixed-dim': '#ffb1c8',
    'on-primary-fixed': '#3e001d',
    'on-primary-fixed-variant': '#8e0040',
    'inverse-primary': '#c2185b',
    secondary: '#e3bdc4',
    'on-secondary': '#422930',
    'secondary-container': '#5a3f45',
    'on-secondary-container': '#ffd9e2',
    'secondary-fixed': '#ffd9e2',
    'secondary-fixed-dim': '#e3bdc4',
    'on-secondary-fixed': '#2b151a',
    'on-secondary-fixed-variant': '#5a3f45',
    tertiary: '#f48fb1',
    'on-tertiary': '#48290c',
    'tertiary-container': '#613f20',
    'on-tertiary-container': '#ffdcc2',
    'tertiary-fixed': '#ffdcc2',
    'tertiary-fixed-dim': '#f48fb1',
    'on-tertiary-fixed': '#2e1500',
    'on-tertiary-fixed-variant': '#613f20',
    'surface-tint': '#ffb1c8',
  },
});

export const violetTheme = buildTheme({
  id: 'violet',
  label: '紫晶',
  swatch: '#7b1fa2',
  accent: '#ce93d8',
  surfaces: {
    light: lightSurfaces('#f9f5fb', {
      low: '#f2ebf7',
      container: '#ebe2f2',
      high: '#e3d8ec',
      highest: '#dccfe6',
      variant: '#e0d4e9',
      dim: '#dccfe6',
    }),
    dark: darkSurfaces('#17141c', {
      low: '#1e1a24',
      container: '#241f2b',
      high: '#2e2936',
      highest: '#393341',
      bright: '#2c2733',
      variant: '#433c4c',
    }),
  },
  light: {
    primary: '#7b1fa2',
    'on-primary': '#ffffff',
    'primary-container': '#f3d9ff',
    'on-primary-container': '#2d004f',
    'primary-fixed': '#f3d9ff',
    'primary-fixed-dim': '#e2b6ff',
    'on-primary-fixed': '#2d004f',
    'on-primary-fixed-variant': '#5e0080',
    'inverse-primary': '#e2b6ff',
    secondary: '#68596d',
    'on-secondary': '#ffffff',
    'secondary-container': '#efdcf4',
    'on-secondary-container': '#231728',
    'secondary-fixed': '#efdcf4',
    'secondary-fixed-dim': '#d3c0d7',
    'on-secondary-fixed': '#231728',
    'on-secondary-fixed-variant': '#4f4255',
    tertiary: '#815251',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#ffdad8',
    'on-tertiary-container': '#331111',
    'tertiary-fixed': '#ffdad8',
    'tertiary-fixed-dim': '#ce93d8',
    'on-tertiary-fixed': '#331111',
    'on-tertiary-fixed-variant': '#663b3a',
    'surface-tint': '#7b1fa2',
  },
  dark: {
    primary: '#e2b6ff',
    'on-primary': '#4a0072',
    'primary-container': '#5e0080',
    'on-primary-container': '#f3d9ff',
    'primary-fixed': '#f3d9ff',
    'primary-fixed-dim': '#e2b6ff',
    'on-primary-fixed': '#2d004f',
    'on-primary-fixed-variant': '#5e0080',
    'inverse-primary': '#7b1fa2',
    secondary: '#d3c0d7',
    'on-secondary': '#382c3d',
    'secondary-container': '#4f4255',
    'on-secondary-container': '#efdcf4',
    'secondary-fixed': '#efdcf4',
    'secondary-fixed-dim': '#d3c0d7',
    'on-secondary-fixed': '#231728',
    'on-secondary-fixed-variant': '#4f4255',
    tertiary: '#ce93d8',
    'on-tertiary': '#4c2525',
    'tertiary-container': '#663b3a',
    'on-tertiary-container': '#ffdad8',
    'tertiary-fixed': '#ffdad8',
    'tertiary-fixed-dim': '#ce93d8',
    'on-tertiary-fixed': '#331111',
    'on-tertiary-fixed-variant': '#663b3a',
    'surface-tint': '#e2b6ff',
  },
});

export const emberTheme = buildTheme({
  id: 'ember',
  label: '余烬',
  swatch: '#e65100',
  accent: '#ffb74d',
  surfaces: {
    light: lightSurfaces('#fff7f2', {
      low: '#feeee6',
      container: '#fce6db',
      high: '#f9ddd0',
      highest: '#f5d4c5',
      variant: '#f7d9cb',
      dim: '#f5d4c5',
    }),
    dark: darkSurfaces('#1c1512', {
      low: '#251c18',
      container: '#2c221d',
      high: '#372c26',
      highest: '#423730',
      bright: '#332923',
      variant: '#4a3d36',
    }),
  },
  light: {
    primary: '#e65100',
    'on-primary': '#ffffff',
    'primary-container': '#ffdbcb',
    'on-primary-container': '#341100',
    'primary-fixed': '#ffdbcb',
    'primary-fixed-dim': '#ffb692',
    'on-primary-fixed': '#341100',
    'on-primary-fixed-variant': '#b33d00',
    'inverse-primary': '#ffb692',
    secondary: '#765848',
    'on-secondary': '#ffffff',
    'secondary-container': '#ffdbcb',
    'on-secondary-container': '#2c160a',
    'secondary-fixed': '#ffdbcb',
    'secondary-fixed-dim': '#e6beab',
    'on-secondary-fixed': '#2c160a',
    'on-secondary-fixed-variant': '#5c4132',
    tertiary: '#656032',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#ede4aa',
    'on-tertiary-container': '#1f1c00',
    'tertiary-fixed': '#ede4aa',
    'tertiary-fixed-dim': '#ffb74d',
    'on-tertiary-fixed': '#1f1c00',
    'on-tertiary-fixed-variant': '#4d481d',
    'surface-tint': '#e65100',
  },
  dark: {
    primary: '#ffb692',
    'on-primary': '#561f00',
    'primary-container': '#b33d00',
    'on-primary-container': '#ffdbcb',
    'primary-fixed': '#ffdbcb',
    'primary-fixed-dim': '#ffb692',
    'on-primary-fixed': '#341100',
    'on-primary-fixed-variant': '#b33d00',
    'inverse-primary': '#e65100',
    secondary: '#e6beab',
    'on-secondary': '#432b1e',
    'secondary-container': '#5c4132',
    'on-secondary-container': '#ffdbcb',
    'secondary-fixed': '#ffdbcb',
    'secondary-fixed-dim': '#e6beab',
    'on-secondary-fixed': '#2c160a',
    'on-secondary-fixed-variant': '#5c4132',
    tertiary: '#ffb74d',
    'on-tertiary': '#353107',
    'tertiary-container': '#4d481d',
    'on-tertiary-container': '#ede4aa',
    'tertiary-fixed': '#ede4aa',
    'tertiary-fixed-dim': '#ffb74d',
    'on-tertiary-fixed': '#1f1c00',
    'on-tertiary-fixed-variant': '#4d481d',
    'surface-tint': '#ffb692',
  },
});

export const indigoTheme = buildTheme({
  id: 'indigo',
  label: '靛蓝',
  swatch: '#3949ab',
  accent: '#9fa8da',
  surfaces: {
    light: lightSurfaces('#f4f5fb', {
      low: '#eaebf6',
      container: '#e1e3f1',
      high: '#d8daeb',
      highest: '#cfd2e5',
      variant: '#d4d7e8',
      dim: '#cfd2e5',
    }),
    dark: darkSurfaces('#14151d', {
      low: '#1a1b25',
      container: '#1f202c',
      high: '#292a38',
      highest: '#343544',
      bright: '#262735',
      variant: '#3e3f50',
    }),
  },
  light: {
    primary: '#3949ab',
    'on-primary': '#ffffff',
    'primary-container': '#e0e0ff',
    'on-primary-container': '#00006e',
    'primary-fixed': '#e0e0ff',
    'primary-fixed-dim': '#bec2ff',
    'on-primary-fixed': '#00006e',
    'on-primary-fixed-variant': '#2f3994',
    'inverse-primary': '#bec2ff',
    secondary: '#5c5d72',
    'on-secondary': '#ffffff',
    'secondary-container': '#e1e0f9',
    'on-secondary-container': '#191a2c',
    'secondary-fixed': '#e1e0f9',
    'secondary-fixed-dim': '#c5c4dd',
    'on-secondary-fixed': '#191a2c',
    'on-secondary-fixed-variant': '#444559',
    tertiary: '#78536b',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#ffd8ee',
    'on-tertiary-container': '#2e1126',
    'tertiary-fixed': '#ffd8ee',
    'tertiary-fixed-dim': '#9fa8da',
    'on-tertiary-fixed': '#2e1126',
    'on-tertiary-fixed-variant': '#5e3c52',
    'surface-tint': '#3949ab',
  },
  dark: {
    primary: '#bec2ff',
    'on-primary': '#161f78',
    'primary-container': '#2f3994',
    'on-primary-container': '#e0e0ff',
    'primary-fixed': '#e0e0ff',
    'primary-fixed-dim': '#bec2ff',
    'on-primary-fixed': '#00006e',
    'on-primary-fixed-variant': '#2f3994',
    'inverse-primary': '#3949ab',
    secondary: '#c5c4dd',
    'on-secondary': '#2e2f42',
    'secondary-container': '#444559',
    'on-secondary-container': '#e1e0f9',
    'secondary-fixed': '#e1e0f9',
    'secondary-fixed-dim': '#c5c4dd',
    'on-secondary-fixed': '#191a2c',
    'on-secondary-fixed-variant': '#444559',
    tertiary: '#9fa8da',
    'on-tertiary': '#45263c',
    'tertiary-container': '#5e3c52',
    'on-tertiary-container': '#ffd8ee',
    'tertiary-fixed': '#ffd8ee',
    'tertiary-fixed-dim': '#9fa8da',
    'on-tertiary-fixed': '#2e1126',
    'on-tertiary-fixed-variant': '#5e3c52',
    'surface-tint': '#bec2ff',
  },
});

export const sandTheme = buildTheme({
  id: 'sand',
  label: '沙丘',
  swatch: '#8d6e63',
  accent: '#ffcc80',
  surfaces: {
    light: lightSurfaces('#faf7f4', {
      low: '#f4efe9',
      container: '#eee7e0',
      high: '#e8dfd6',
      highest: '#e1d7cd',
      variant: '#e5dbd1',
      dim: '#e1d7cd',
    }),
    dark: darkSurfaces('#1a1714', {
      low: '#221e1a',
      container: '#28231f',
      high: '#332d28',
      highest: '#3e3731',
      bright: '#2f2924',
      variant: '#463f38',
    }),
  },
  light: {
    primary: '#8d6e63',
    'on-primary': '#ffffff',
    'primary-container': '#ffdbcf',
    'on-primary-container': '#32120a',
    'primary-fixed': '#ffdbcf',
    'primary-fixed-dim': '#e5b9ab',
    'on-primary-fixed': '#32120a',
    'on-primary-fixed-variant': '#6f564c',
    'inverse-primary': '#e5b9ab',
    secondary: '#77574d',
    'on-secondary': '#ffffff',
    'secondary-container': '#ffdbcf',
    'on-secondary-container': '#2c160e',
    'secondary-fixed': '#ffdbcf',
    'secondary-fixed-dim': '#e7bdb1',
    'on-secondary-fixed': '#2c160e',
    'on-secondary-fixed-variant': '#5d4037',
    tertiary: '#6b5e2f',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#f4e2a7',
    'on-tertiary-container': '#221b00',
    'tertiary-fixed': '#f4e2a7',
    'tertiary-fixed-dim': '#ffcc80',
    'on-tertiary-fixed': '#221b00',
    'on-tertiary-fixed-variant': '#52461a',
    'surface-tint': '#8d6e63',
  },
  dark: {
    primary: '#e5b9ab',
    'on-primary': '#4a281f',
    'primary-container': '#6f564c',
    'on-primary-container': '#ffdbcf',
    'primary-fixed': '#ffdbcf',
    'primary-fixed-dim': '#e5b9ab',
    'on-primary-fixed': '#32120a',
    'on-primary-fixed-variant': '#6f564c',
    'inverse-primary': '#8d6e63',
    secondary: '#e7bdb1',
    'on-secondary': '#442a21',
    'secondary-container': '#5d4037',
    'on-secondary-container': '#ffdbcf',
    'secondary-fixed': '#ffdbcf',
    'secondary-fixed-dim': '#e7bdb1',
    'on-secondary-fixed': '#2c160e',
    'on-secondary-fixed-variant': '#5d4037',
    tertiary: '#ffcc80',
    'on-tertiary': '#393005',
    'tertiary-container': '#52461a',
    'on-tertiary-container': '#f4e2a7',
    'tertiary-fixed': '#f4e2a7',
    'tertiary-fixed-dim': '#ffcc80',
    'on-tertiary-fixed': '#221b00',
    'on-tertiary-fixed-variant': '#52461a',
    'surface-tint': '#e5b9ab',
  },
});
