/**
 * Generates src/styles/generated/themes.css from the theme registry.
 * Only brand roles are emitted per data-theme; neutrals live in global.css light/dark.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BRAND_ROLES, COLOR_ROLES } from '../src/styles/themes/roles.ts';
import { themes } from '../src/styles/themes/index.ts';
import type { ColorScheme } from '../src/styles/themes/types.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '../src/styles/generated/themes.css');

function assertScheme(id: string, mode: 'light' | 'dark', scheme: ColorScheme) {
  const missing = COLOR_ROLES.filter((role) => !(role in scheme) || !scheme[role]);
  if (missing.length) {
    throw new Error(`[generate-themes] Theme "${id}" ${mode} missing roles: ${missing.join(', ')}`);
  }
}

function brandToCss(scheme: ColorScheme, indent = '  '): string {
  return BRAND_ROLES.map((role) => `${indent}--color-${role}: ${scheme[role]};`).join('\n');
}

function buildCss(): string {
  const blocks: string[] = [
    '/* AUTO-GENERATED by scripts/generate-themes.ts — do not edit by hand */',
    '/* Brand colors only; light/dark neutrals are in global.css */',
    '',
  ];

  for (const theme of themes) {
    assertScheme(theme.id, 'light', theme.light);
    assertScheme(theme.id, 'dark', theme.dark);

    // Canonical brand = light scheme (unchanged when toggling 浅色/深色)
    blocks.push(`/* Theme: ${theme.label} (${theme.id}) — brand only */`);
    blocks.push(`html[data-theme="${theme.id}"] {`);
    blocks.push(brandToCss(theme.light));
    blocks.push('}');
    blocks.push('');
  }

  return blocks.join('\n');
}

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, buildCss(), 'utf8');
console.log(`[generate-themes] Wrote ${outPath} (${themes.length} theme(s), brand-only)`);
